name: linkwarden
services:
  ### Postgres
  postgres:
    image: postgres:16-alpine
    env_file: .env
    restart: always
    volumes:
      - ./.data/pgdata:/var/lib/postgresql/data

  ### Linkwarden
  linkwarden:
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
    restart: always
    # build: . # uncomment this line to build from source
    image: ghcr.io/linkwarden/linkwarden:latest # comment this line to build from source
    ports:
      - 3000:3000
    volumes:
      - ./.data/linkwarden:/data/data
    depends_on:
      - postgres